use futbol;
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1967-08-22','India','Taiwan','Taiwan');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1971-11-14','South Korea','Vietnam Republic','South Korea');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1972-05-07','South Korea','Iraq','Iraq');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1972-05-17','Thailand','South Korea','South Korea');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1972-05-19','Thailand','Cambodia','Thailand');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1973-04-21','Senegal','Ghana','Ghana');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1973-06-14','Guinea','Mali','Guinea');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1973-06-14','Mauritius','Tanzania','Mauritius');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1973-07-26','Malaysia','Kuwait','Malaysia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1973-07-26','Cambodia','Singapore','Singapore');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1973-07-27','Bangladesh','Thailand','Thailand');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1973-07-28','Myanmar','South Korea','Myanmar');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1973-08-09','India','Vietnam Republic','Vietnam Republic');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1973-08-23','Algeria','Syria','Syria');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1973-08-25','Algeria','Iraq','Algeria');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1974-03-28','Qatar','United Arab Emirates','Qatar');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1974-07-24','Hong Kong','Indonesia','Indonesia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1974-08-01','India','Indonesia','Indonesia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1974-10-09','Syria','Morocco','Morocco');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1974-11-22','Libya','Tunisia','Tunisia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1974-12-18','South Korea','Malaysia','South Korea');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1975-07-13','Morocco','Ghana','Morocco');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1975-11-09','Kenya','Malawi','Kenya');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1975-12-23','Libya','Syria','Syria');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1976-06-20','Czechoslovakia','Germany','Czechoslovakia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1976-12-22','South Korea','Malaysia','Malaysia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1977-01-09','Tunisia','Morocco','Tunisia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1977-03-22','Argentina','Iran','Argentina');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1977-06-26','Zambia','Algeria','Zambia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1977-07-27','Iran','Morocco','Iran');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1977-08-31','Paraguay','Argentina','Paraguay');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1979-01-13','Guinea-Bissau','Mali','Mali');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1979-01-14','Guinea-Bissau','Guinea','Guinea');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1979-04-29','Cameroon','Guinea','Guinea');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1979-05-22','Argentina','Netherlands','Argentina');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1980-02-16','Gambia','Mauritania','Gambia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1980-03-19','Algeria','Egypt','Algeria');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1980-06-21','Italy','Czechoslovakia','Czechoslovakia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1980-07-12','Nigeria','Tunisia','Nigeria');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1980-11-30','Zambia','Morocco','Morocco');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1980-12-31','Hong Kong','China PR','China PR');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1981-02-13','Mali','Guinea','Guinea');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1981-05-10','Rwanda','Ethiopia','Ethiopia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1982-02-21','Ivory Coast','Togo','Togo');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1982-02-22','Ivory Coast','Burkina Faso','Burkina Faso');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1982-03-19','Libya','Ghana','Ghana');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1982-05-15','Thailand','Singapore','Thailand');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1982-05-17','Thailand','South Korea','Thailand');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1982-07-08','Germany','France','Germany');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1982-10-17','Indonesia','Malaysia','Indonesia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1982-11-27','Uganda','Kenya','Kenya');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1983-02-06','Senegal','Niger','Senegal');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1983-02-20','Gambia','Sierra Leone','Gambia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1983-02-27','Mali','Guinea','Mali');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1983-04-22','Egypt','Congo','Egypt');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1983-04-24','Mauritius','Ethiopia','Ethiopia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1983-07-18','Hong Kong','Thailand','Thailand');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1983-08-28','Morocco','Nigeria','Nigeria');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1983-10-20','Brazil','Paraguay','Brazil');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1983-12-15','Ivory Coast','Mali','Ivory Coast');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1983-12-18','Mali','Nigeria','Mali');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1984-02-16','Sierra Leone','Mali','Sierra Leone');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1984-02-19','Sierra Leone','Senegal','Senegal');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1984-03-14','Egypt','Nigeria','Nigeria');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1984-03-14','Algeria','Cameroon','Cameroon');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1984-03-28','Iraq','Qatar','Iraq');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1984-06-24','Denmark','Spain','Spain');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1984-07-15','Senegal','Angola','Angola');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1984-11-23','Kenya','Somalia','Kenya');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1984-11-28','Ghana','Togo','Ghana');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1984-12-08','Kenya','Somalia','Kenya');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1984-12-13','Saudi Arabia','Iran','Saudi Arabia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1984-12-15','Malawi','Zambia','Zambia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1984-12-16','Iran','Kuwait','Kuwait');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1984-12-16','Chad','Equatorial Guinea','Chad');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1984-12-19','Central African Republic','Gabon','Gabon');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1984-12-20','Congo','Cameroon','Cameroon');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1985-04-16','Mozambique','Malawi','Mozambique');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1985-04-21','Madagascar','Egypt','Egypt');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1985-07-10','Bahrain','Qatar','Bahrain');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1985-07-12','Saudi Arabia','Qatar','Saudi Arabia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1985-08-25','Mali','Guinea','Guinea');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1985-09-15','Mozambique','Libya','Mozambique');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1985-10-11','Kenya','Uganda','Kenya');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1986-03-21','Egypt','Cameroon','Egypt');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1986-06-21','Brazil','France','France');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1986-06-21','Mexico','Germany','Germany');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1986-06-22','Spain','Belgium','Belgium');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1986-10-19','Gabon','Angola','Angola');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1986-12-17','Chad','Gabon','Chad');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1987-03-01','Mali','Sierra Leone','Mali');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1987-03-02','Senegal','Sierra Leone','Senegal');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1987-06-19','Australia','Egypt','Australia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1987-06-21','South Korea','Australia','South Korea');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1987-07-19','DR Congo','Senegal','DR Congo');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1987-12-13','Malawi','Zimbabwe','Zimbabwe');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1987-12-18','Equatorial Guinea','Gabon','Gabon');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1987-12-27','Ethiopia','Zimbabwe','Ethiopia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1988-01-06','South Korea','Egypt','South Korea');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1988-03-23','Algeria','Nigeria','Nigeria');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1988-03-26','Morocco','Algeria','Algeria');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1988-03-31','Germany','Sweden','Sweden');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1988-05-05','Mali','Senegal','Mali');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1988-05-08','Guinea','Mali','Guinea');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1988-05-28','Canada','Greece','Canada');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1988-07-19','Egypt','Syria','Syria');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1988-07-21','Iraq','Syria','Iraq');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1988-09-29','Chile','Ecuador','Ecuador');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1988-10-16','Eswatini','Tanzania','Eswatini');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1988-12-06','Central African Republic','Gabon','Gabon');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1988-12-17','China PR','Iran','Iran');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1988-12-18','South Korea','Saudi Arabia','Saudi Arabia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1989-04-23','Ghana','Gabon','Gabon');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1989-04-23','Kenya','Sudan','Kenya');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1989-11-08','Iran','Uganda','Uganda');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1989-11-12','Iraq','Uganda','Iraq');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1989-12-11','Chad','Cameroon','Cameroon');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1989-12-16','Malawi','Uganda','Uganda');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1990-01-28','Nigeria','Senegal','Nigeria');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1990-02-04','United States','Colombia','Colombia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1990-02-20','Colombia','Russia','Colombia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1990-05-18','Zimbabwe','Eswatini','Zimbabwe');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1990-06-25','Republic of Ireland','Romania','Republic of Ireland');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1990-06-30','Yugoslavia','Argentina','Argentina');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1990-07-03','Italy','Argentina','Argentina');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1990-07-04','Germany','England','Germany');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1990-08-03','China PR','South Korea','South Korea');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1990-12-17','Tanzania','Uganda','Uganda');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1990-12-17','Central African Republic','Equatorial Guinea','Central African Republic');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1991-01-21','Cameroon','Algeria','Cameroon');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1991-01-21','Senegal','Ivory Coast','Ivory Coast');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1991-01-22','Senegal','Algeria','Senegal');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1991-01-23','Ivory Coast','Cameroon','Ivory Coast');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1991-06-14','South Korea','Australia','South Korea');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1991-06-16','Italy','Russia','Italy');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1991-07-07','United States','Honduras','United States');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1991-08-08','Czechoslovakia','Yugoslavia','Czechoslovakia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1991-09-20','Fiji','Solomon Islands','Fiji');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1991-09-28','Egypt','Mali','Egypt');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1992-01-23','Cameroon','Ivory Coast','Ivory Coast');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1992-01-26','Ghana','Ivory Coast','Ivory Coast');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1992-06-22','Netherlands','Denmark','Denmark');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1992-06-27','Cuba','Martinique','Martinique');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1992-08-29','Japan','South Korea','Japan');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1992-09-15','Syria','Egypt','Egypt');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1992-11-08','China PR','United Arab Emirates','China PR');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1992-11-25','Uganda','Zambia','Uganda');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1993-01-23','Japan','Switzerland','Switzerland');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1993-02-20','Finland','Estonia','Finland');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1993-02-24','Argentina','Denmark','Argentina');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1993-05-27','Bolivia','Paraguay','Bolivia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1993-05-28','Martinique','Saint Kitts and Nevis','Martinique');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1993-05-30','Jamaica','Martinique','Martinique');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1993-06-26','Colombia','Uruguay','Colombia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1993-06-27','Brazil','Argentina','Argentina');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1993-07-01','Colombia','Argentina','Argentina');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1993-08-15','Australia','Canada','Australia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1993-10-24','Burundi','Guinea','Guinea');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1994-01-29','Burkina Faso','Guinea','Burkina Faso');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1994-04-06','Nigeria','Ivory Coast','Nigeria');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1994-07-05','Mexico','Bulgaria','Bulgaria');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1994-07-10','Romania','Sweden','Sweden');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1994-07-17','Brazil','Italy','Brazil');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1994-12-08','Tanzania','Uganda','Tanzania');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1995-01-10','Denmark','Mexico','Denmark');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1995-01-13','Mexico','Nigeria','Mexico');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1995-02-26','Japan','South Korea','Japan');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1995-03-31','India','Bangladesh','India');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1995-05-21','Antigua and Barbuda','Saint Kitts and Nevis','Antigua and Barbuda');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1995-06-09','Paraguay','Bolivia','Paraguay');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1995-07-16','Paraguay','Colombia','Colombia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1995-07-17','United States','Mexico','United States');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1995-07-17','Brazil','Argentina','Brazil');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1995-07-23','Uruguay','Brazil','Uruguay');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1995-08-24','Fiji','Solomon Islands','Solomon Islands');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1995-11-28','Mauritania','Sierra Leone','Sierra Leone');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1995-12-02','Gabon','Cameroon','Cameroon');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1995-12-02','Algeria','Ivory Coast','Ivory Coast');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1995-12-06','Ethiopia','Zanzibar','Zanzibar');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1995-12-07','Honduras','Costa Rica','Honduras');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1996-01-28','Gabon','Tunisia','Tunisia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1996-02-22','Japan','Sweden','Sweden');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1996-04-28','Barbados','Jamaica','Jamaica');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1996-05-05','Guyana','Suriname','Suriname');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1996-06-05','Martinique','Suriname','Martinique');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1996-06-22','England','Spain','England');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1996-06-22','France','Netherlands','France');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1996-06-26','France','Czech Republic','Czech Republic');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1996-06-26','England','Germany','Germany');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1996-08-25','Ethiopia','Uganda','Ethiopia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1996-11-29','Sudan','Kenya','Sudan');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1996-12-11','Morocco','Croatia','Croatia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1996-12-12','Croatia','Czech Republic','Croatia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1996-12-19','Iran','Saudi Arabia','Saudi Arabia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1996-12-21','Iran','Kuwait','Iran');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1996-12-21','United Arab Emirates','Saudi Arabia','Saudi Arabia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1996-12-27','Benin','Burkina Faso','Benin');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1997-02-07','Russia','Serbia','Russia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1997-04-10','India','Iraq','Iraq');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1997-06-22','Ecuador','Mexico','Mexico');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1997-07-10','Trinidad and Tobago','Jamaica','Trinidad and Tobago');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1997-10-20','Haiti','Cuba','Haiti');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1997-10-22','Cuba','Cameroon','Cuba');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1997-12-07','Gambia','Guinea','Guinea');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1998-01-31','Egypt','South Korea','South Korea');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1998-01-31','Iran','Chile','Iran');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1998-02-21','Burkina Faso','Tunisia','Burkina Faso');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1998-02-21','Ivory Coast','Egypt','Egypt');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1998-02-27','Burkina Faso','DR Congo','DR Congo');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1998-04-22','Hungary','North Macedonia','Hungary');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1998-05-29','Belgium','England','Belgium');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1998-05-29','Morocco','France','Morocco');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1998-06-30','Argentina','England','Argentina');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1998-07-03','France','Italy','France');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1998-07-07','Brazil','Netherlands','Brazil');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1998-09-05','Indonesia','Thailand','Indonesia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1998-11-17','Guatemala','Honduras','Guatemala');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1998-11-18','Guatemala','Mexico','Guatemala');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1998-12-02','United Arab Emirates','North Korea','United Arab Emirates');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1999-05-22','Malawi','Namibia','Namibia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1999-06-16','Thailand','New Zealand','Thailand');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1999-06-19','New Zealand','Poland','Poland');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1999-07-10','Mexico','Peru','Mexico');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1999-07-10','Paraguay','Uruguay','Uruguay');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1999-07-13','Uruguay','Chile','Uruguay');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1999-07-18','Eswatini','Zimbabwe','Eswatini');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1999-07-31','Namibia','South Africa','Namibia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1999-08-03','Rwanda','Kenya','Kenya');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1999-08-07','Rwanda','Burundi','Rwanda');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1999-08-07','Zambia','Mozambique','Zambia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1999-08-28','Namibia','Eswatini','Namibia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('1999-11-26','Gabon','Togo','Togo');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2000-02-04','Romania','Georgia','Romania');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2000-02-12','South Africa','Tunisia','South Africa');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2000-02-13','Nigeria','Cameroon','Cameroon');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2000-02-19','United States','Colombia','Colombia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2000-03-19','Suriname','Saint Lucia','Suriname');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2000-04-29','British Virgin Islands','Sint Maarten','British Virgin Islands');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2000-04-30','British Virgin Islands','Antigua and Barbuda','Antigua and Barbuda');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2000-05-10','Maldives','Sri Lanka','Sri Lanka');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2000-05-11','Senegal','Mali','Senegal');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2000-05-20','Malawi','Angola','Angola');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2000-05-21','Barbados','Cuba','Barbados');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2000-06-04','France','Japan','France');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2000-06-07','Iran','Egypt','Egypt');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2000-06-11','Lesotho','Zambia','Lesotho');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2000-06-29','Netherlands','Italy','Italy');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2000-07-14','Libya','Chad','Libya');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2000-07-16','Mozambique','Lesotho','Lesotho');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2000-09-03','Togo','Sierra Leone','Togo');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2000-10-04','United Arab Emirates','South Korea','United Arab Emirates');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2000-10-28','Kenya','Uganda','Uganda');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2000-12-02','Ethiopia','Rwanda','Ethiopia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2001-01-17','China PR','Egypt','Egypt');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2001-01-27','South Korea','Paraguay','South Korea');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2001-02-11','Eswatini','Zambia','Eswatini');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2001-07-12','Ynys Môn','Jersey','Ynys Môn');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2001-07-13','Guernsey','Ynys Môn','Guernsey');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2001-07-29','Uruguay','Honduras','Honduras');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2001-08-03','China PR','North Korea','North Korea');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2001-08-03','Kuwait','Trinidad and Tobago','Kuwait');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2001-08-05','Kuwait','North Korea','North Korea');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2001-08-18','Zambia','Angola','Angola');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2001-10-24','Kenya','Uganda','Kenya');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2001-10-24','Tanzania','DR Congo','Tanzania');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2001-12-18','Ethiopia','Burundi','Ethiopia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2002-01-06','Martinique','Haiti','Martinique');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2002-01-26','Canada','Martinique','Canada');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2002-01-27','Mexico','South Korea','South Korea');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2002-01-30','United States','Canada','United States');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2002-02-10','Senegal','Cameroon','Cameroon');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2002-02-12','Cyprus','Switzerland','Cyprus');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2002-02-15','China PR','Slovenia','Slovenia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2002-02-16','Thailand','North Korea','North Korea');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2002-03-30','Botswana','South Africa','South Africa');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2002-05-17','Russia','Belarus','Belarus');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2002-05-19','Russia','Serbia','Serbia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2002-06-16','Spain','Republic of Ireland','Spain');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2002-06-22','South Korea','Spain','South Korea');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2002-07-21','South Africa','Madagascar','South Africa');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2002-09-05','Iraq','Iran','Iraq');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2002-09-07','Syria','Iran','Iran');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2002-09-17','Iran','Morocco','Iran');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2002-09-19','Iran','Paraguay','Iran');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2002-10-23','Kenya','South Africa','Kenya');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2002-10-26','Tanzania','South Africa','South Africa');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2002-10-26','Kenya','Uganda','Kenya');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2002-11-19','South Africa','Senegal','Senegal');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2002-12-27','Niger','Burkina Faso','Burkina Faso');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2002-12-29','Niger','Mali','Niger');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2003-01-20','Bangladesh','Maldives','Bangladesh');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2003-02-04','Uruguay','Iran','Uruguay');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2003-03-07','Benin','Niger','Benin');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2003-03-15','Guadeloupe','French Guiana','Guadeloupe');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2003-03-22','Mozambique','Lesotho','Mozambique');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2003-03-27','Tunisia','Ghana','Tunisia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2003-03-30','Ghana','Madagascar','Ghana');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2003-05-24','Botswana','Malawi','Malawi');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2003-07-09','New Caledonia','Vanuatu','New Caledonia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2003-08-16','Malawi','Zambia','Malawi');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2003-09-24','Algeria','Gabon','Algeria');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2003-09-26','Algeria','Burkina Faso','Algeria');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2003-12-08','Kenya','Rwanda','Rwanda');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2003-12-08','Sudan','Uganda','Uganda');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2004-02-11','Tunisia','Nigeria','Tunisia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2004-02-19','Kazakhstan','Armenia','Kazakhstan');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2004-02-28','Lesotho','Botswana','Botswana');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2004-06-23','Jordan','Syria','Syria');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2004-06-24','Portugal','England','Portugal');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2004-06-26','Sweden','Netherlands','Netherlands');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2004-07-18','Angola','Botswana','Angola');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2004-07-21','Uruguay','Brazil','Brazil');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2004-07-25','Argentina','Brazil','Brazil');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2004-07-30','Uzbekistan','Bahrain','Bahrain');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2004-07-31','Japan','Jordan','Japan');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2004-08-03','China PR','Iran','China PR');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2004-10-22','Nigeria','Ecuador','Ecuador');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2004-10-24','Zimbabwe','Zambia','Zambia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2004-11-20','Zambia','Angola','Angola');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2004-11-30','Thailand','Estonia','Thailand');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2004-11-30','Singapore','Hong Kong','Hong Kong');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2004-12-02','Thailand','Slovakia','Slovakia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2004-12-03','Bahrain','Latvia','Bahrain');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2004-12-03','Finland','Oman','Oman');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2004-12-22','Ethiopia','Kenya','Ethiopia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2004-12-24','Qatar','Oman','Qatar');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2005-02-08','Cyprus','Austria','Cyprus');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2005-02-09','Austria','Latvia','Latvia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2005-02-27','Costa Rica','Honduras','Costa Rica');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2005-04-16','Namibia','Botswana','Botswana');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2005-06-26','Mexico','Argentina','Argentina');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2005-07-21','Colombia','Panama','Panama');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2005-07-24','United States','Panama','United States');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2005-07-28','Kuwait','United Arab Emirates','United Arab Emirates');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2005-07-30','Egypt','United Arab Emirates','Egypt');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2005-08-13','South Africa','Zambia','Zambia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2005-08-15','Ukraine','Israel','Israel');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2005-11-16','Australia','Uruguay','Australia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2005-12-10','Syria','Iraq','Iraq');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2005-12-10','Zanzibar','Uganda','Zanzibar');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2006-02-04','Nigeria','Tunisia','Nigeria');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2006-02-04','Cameroon','Ivory Coast','Ivory Coast');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2006-02-10','Egypt','Ivory Coast','Egypt');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2006-02-28','Finland','Kazakhstan','Kazakhstan');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2006-03-01','Finland','Belarus','Finland');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2006-04-29','Lesotho','Mozambique','Lesotho');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2006-04-30','Mauritius','Mozambique','Mozambique');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2006-05-21','Botswana','South Africa','Botswana');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2006-06-03','Northern Cyprus','Zanzibar','Northern Cyprus');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2006-06-26','Switzerland','Ukraine','Ukraine');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2006-06-30','Germany','Argentina','Germany');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2006-07-01','England','Portugal','Portugal');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2006-07-09','Italy','France','Italy');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2006-07-22','Namibia','Seychelles','Seychelles');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2007-04-29','Mozambique','Zimbabwe','Mozambique');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2007-05-26','Malawi','South Africa','South Africa');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2007-05-26','Eswatini','Mauritius','Mauritius');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2007-07-10','Uruguay','Brazil','Brazil');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2007-07-21','Japan','Australia','Japan');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2007-07-22','Iran','South Korea','South Korea');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2007-07-25','Iraq','South Korea','Iraq');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2007-07-28','South Korea','Japan','South Korea');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2007-07-29','Botswana','Angola','Botswana');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2007-10-24','South Africa','Zambia','South Africa');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2008-06-20','Croatia','Turkey','Turkey');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2008-06-22','Spain','Italy','Spain');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2008-07-27','Zambia','Zimbabwe','Zambia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2009-06-26','Provence','Sápmi','Sápmi');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2009-07-23','Costa Rica','Mexico','Mexico');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2009-10-28','Zimbabwe','South Africa','Zimbabwe');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2010-01-25','Zambia','Nigeria','Nigeria');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2010-06-29','Paraguay','Japan','Paraguay');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2010-07-02','Uruguay','Ghana','Uruguay');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2011-01-25','Japan','South Korea','Japan');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2011-02-08','Romania','Ukraine','Ukraine');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2011-02-09','Sweden','Ukraine','Ukraine');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2011-06-08','Uruguay','Netherlands','Uruguay');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2011-06-18','Costa Rica','Honduras','Honduras');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2011-06-19','Panama','El Salvador','Panama');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2011-06-29','Saare County','Åland Islands','Åland Islands');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2011-06-30','Isle of Man','Menorca','Menorca');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2011-07-12','Saint Lucia','Aruba','Saint Lucia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2011-07-16','Argentina','Uruguay','Uruguay');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2011-07-17','Brazil','Paraguay','Paraguay');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2011-07-20','Paraguay','Venezuela','Paraguay');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2012-02-05','Gabon','Mali','Mali');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2012-02-12','Zambia','Ivory Coast','Zambia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2012-06-03','Finland','Latvia','Latvia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2012-06-24','England','Italy','Italy');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2012-06-27','Portugal','Spain','Spain');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2012-11-21','Argentina','Brazil','Brazil');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2013-01-23','Sweden','North Korea','Sweden');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2013-02-02','South Africa','Mali','Mali');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2013-02-06','Burkina Faso','Ghana','Burkina Faso');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2013-06-27','Spain','Italy','Spain');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2013-06-30','Uruguay','Italy','Italy');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2013-07-13','Zimbabwe','Malawi','Zimbabwe');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2013-07-14','Angola','Lesotho','Lesotho');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2013-07-17','Zambia','South Africa','Zambia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2014-05-29','Latvia','Estonia','Latvia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2014-06-04','Abkhazia','South Ossetia','South Ossetia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2014-06-04','Ellan Vannin','Iraqi Kurdistan','Ellan Vannin');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2014-06-05','Padania','Abkhazia','Padania');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2014-06-05','Occitania','Iraqi Kurdistan','Iraqi Kurdistan');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2014-06-07','Padania','Iraqi Kurdistan','Padania');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2014-06-08','County of Nice','Ellan Vannin','County of Nice');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2014-06-28','Brazil','Chile','Brazil');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2014-06-29','Costa Rica','Greece','Costa Rica');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2014-07-05','Netherlands','Costa Rica','Netherlands');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2014-07-09','Netherlands','Argentina','Argentina');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2015-01-23','Iran','Iraq','Iraq');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2015-01-23','Japan','United Arab Emirates','United Arab Emirates');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2015-01-30','Curaçao','Aruba','Aruba');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2015-02-07','Equatorial Guinea','DR Congo','DR Congo');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2015-02-08','Ivory Coast','Ghana','Ivory Coast');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2015-05-24','Zambia','Namibia','Namibia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2015-05-24','South Africa','Botswana','Botswana');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2015-05-25','Mozambique','Malawi','Mozambique');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2015-05-27','South Africa','Malawi','Malawi');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2015-06-21','Ellan Vannin','Felvidék','Ellan Vannin');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2015-06-26','Argentina','Colombia','Argentina');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2015-06-27','Brazil','Paraguay','Paraguay');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2015-07-02','Gibraltar','Åland Islands','Åland Islands');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2015-07-04','Chile','Argentina','Chile');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2015-07-04','Zambia','Namibia','Zambia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2015-07-19','Trinidad and Tobago','Panama','Panama');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2015-07-25','United States','Panama','Panama');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2015-10-13','El Salvador','Guatemala','Guatemala');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2016-02-03','DR Congo','Guinea','DR Congo');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2016-05-27','Corsica','Basque Country','Basque Country');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2016-06-01','United Koreans in Japan','Northern Cyprus','Northern Cyprus');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2016-06-02','Iraqi Kurdistan','Padania','Padania');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2016-06-03','Bosnia and Herzegovina','Denmark','Bosnia and Herzegovina');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2016-06-03','Thailand','Syria','Thailand');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2016-06-03','Vietnam','Hong Kong','Vietnam');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2016-06-03','Iraqi Kurdistan','Western Armenia','Western Armenia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2016-06-03','Chagos Islands','Raetia','Raetia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2016-06-04','United Koreans in Japan','Iraqi Kurdistan','United Koreans in Japan');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2016-06-05','Abkhazia','Panjab','Abkhazia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2016-06-11','Papua New Guinea','New Zealand','New Zealand');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2016-06-17','Peru','Colombia','Colombia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2016-06-18','Namibia','Botswana','Botswana');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2016-06-18','South Africa','Lesotho','South Africa');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2016-06-19','Zambia','Eswatini','Eswatini');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2016-06-22','Botswana','DR Congo','Botswana');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2016-06-25','Switzerland','Poland','Poland');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2016-06-26','Argentina','Chile','Chile');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2016-06-30','Poland','Portugal','Portugal');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2016-07-02','Germany','Italy','Germany');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2017-01-11','Chile','Croatia','Chile');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2017-01-14','China PR','Croatia','China PR');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2017-02-01','Burkina Faso','Egypt','Egypt');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2017-06-09','Kárpátalja','Ellan Vannin','Kárpátalja');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2017-06-09','Padania','Abkhazia','Padania');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2017-06-10','Northern Cyprus','Padania','Padania');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2017-06-28','Portugal','Chile','Chile');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2017-06-29','Hitra','Western Isles','Western Isles');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2017-06-29','Greenland','Menorca','Greenland');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2017-07-01','Namibia','Lesotho','Lesotho');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2017-07-07','Tanzania','Lesotho','Tanzania');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2017-07-16','Thailand','Belarus','Thailand');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2018-03-21','South Africa','Angola','South Africa');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2018-03-21','Zambia','Zimbabwe','Zambia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2018-03-22','Thailand','Gabon','Thailand');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2018-03-24','Angola','Zimbabwe','Angola');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2018-06-02','Zambia','Namibia','Zambia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2018-06-03','Andorra','Cape Verde','Cape Verde');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2018-06-03','South Africa','Madagascar','Madagascar');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2018-06-03','Zimbabwe','Botswana','Zimbabwe');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2018-06-05','Matabeleland','Kabylia','Kabylia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2018-06-06','Lesotho','Zimbabwe','Zimbabwe');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2018-06-09','Tibet','United Koreans in Japan','United Koreans in Japan');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2018-06-09','Panjab','Cascadia','Panjab');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2018-06-09','Padania','Székely Land','Padania');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2018-06-09','Northern Cyprus','Kárpátalja','Kárpátalja');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2018-07-01','Russia','Spain','Russia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2018-07-01','Croatia','Denmark','Croatia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2018-07-03','Colombia','England','England');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2018-07-07','Russia','Croatia','Croatia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2019-01-20','Jordan','Vietnam','Vietnam');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2019-01-21','Australia','Uzbekistan','Australia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2019-03-23','Oman','Singapore','Oman');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2019-06-01','Lesotho','Uganda','Lesotho');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2019-06-02','South Africa','Botswana','Botswana');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2019-06-02','Zambia','Malawi','Zambia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2019-06-04','South Africa','Uganda','South Africa');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2019-06-05','Zimbabwe','Zambia','Zambia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2019-06-06','Abkhazia','Western Armenia','Western Armenia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2019-06-06','South Ossetia','Chameria','South Ossetia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2019-06-07','Lesotho','Zimbabwe','Zimbabwe');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2019-06-07','South Africa','Malawi','South Africa');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2019-06-08','Abkhazia','Chameria','Abkhazia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2019-06-09','Switzerland','England','England');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2019-06-27','Brazil','Paraguay','Brazil');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2019-06-28','Colombia','Chile','Chile');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2019-06-29','Mexico','Costa Rica','Mexico');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2019-06-29','Uruguay','Peru','Peru');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2019-07-05','Morocco','Benin','Benin');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2019-07-07','Madagascar','DR Congo','Madagascar');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2019-07-08','Ghana','Tunisia','Tunisia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2019-07-11','Ivory Coast','Algeria','Algeria');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2019-09-08','Tanzania','Burundi','Tanzania');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2019-10-13','Chad','Liberia','Chad');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2019-10-13','Gambia','Djibouti','Gambia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2020-10-08','Bosnia and Herzegovina','Northern Ireland','Northern Ireland');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2020-10-08','Slovakia','Republic of Ireland','Slovakia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2020-10-08','Scotland','Israel','Scotland');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2020-11-12','Serbia','Scotland','Scotland');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2021-06-03','Mexico','Costa Rica','Mexico');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2021-06-06','Honduras','Costa Rica','Honduras');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2021-06-28','France','Switzerland','Switzerland');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2021-07-02','Peru','Paraguay','Peru');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2021-07-02','Switzerland','Spain','Spain');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2021-07-03','Uruguay','Colombia','Colombia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2021-07-06','Italy','Spain','Italy');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2021-07-06','Trinidad and Tobago','French Guiana','Trinidad and Tobago');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2021-07-06','Argentina','Colombia','Argentina');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2021-07-06','Guatemala','Guadeloupe','Guadeloupe');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2021-07-11','England','Italy','Italy');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2021-07-16','Senegal','Eswatini','Senegal');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2021-07-18','Eswatini','Mozambique','Eswatini');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2021-07-18','South Africa','Senegal','South Africa');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2021-11-19','Sri Lanka','Seychelles','Seychelles');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2021-12-11','Morocco','Algeria','Algeria');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2021-12-18','Qatar','Egypt','Qatar');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2022-01-23','Burkina Faso','Gabon','Burkina Faso');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2022-01-26','Ivory Coast','Egypt','Egypt');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2022-01-26','Mali','Equatorial Guinea','Equatorial Guinea');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2022-02-03','Cameroon','Egypt','Egypt');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2022-02-05','Cameroon','Burkina Faso','Cameroon');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2022-02-06','Senegal','Egypt','Senegal');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2022-03-25','Tajikistan','Uganda','Uganda');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2022-03-29','Kazakhstan','Moldova','Kazakhstan');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2022-03-29','Senegal','Egypt','Senegal');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2022-06-13','Australia','Peru','Australia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2022-06-14','Chile','Ghana','Ghana');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2022-09-22','Thailand','Malaysia','Malaysia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2022-09-23','Iraq','Oman','Oman');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2022-09-25','Malaysia','Tajikistan','Tajikistan');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2022-11-16','Lithuania','Iceland','Iceland');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2022-11-16','Latvia','Estonia','Latvia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2022-11-19','Latvia','Iceland','Iceland');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2022-12-05','Japan','Croatia','Croatia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2022-12-06','Morocco','Spain','Morocco');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2022-12-09','Croatia','Brazil','Croatia');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2022-12-09','Netherlands','Argentina','Argentina');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2022-12-18','Argentina','France','Argentina');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2023-06-16','Curaçao','Saint Kitts and Nevis','Saint Kitts and Nevis');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2023-06-17','Guyana','Grenada','Guyana');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2023-06-17','Suriname','Puerto Rico','Puerto Rico');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2023-06-18','Croatia','Spain','Spain');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2023-06-20','Saint Kitts and Nevis','French Guiana','Saint Kitts and Nevis');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2023-07-01','India','Lebanon','India');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2023-07-04','India','Kuwait','India');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2023-07-09','United States','Canada','United States');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2023-07-12','United States','Panama','Panama');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2023-09-07','Iraq','India','Iraq');
INSERT INTO shootout(dates,home_team,away_team,winner) VALUES ('2023-09-10','Thailand','Iraq','Iraq');
